### Site metadata ###

site_name: PatchCableMgr
site_description: PatchCableMgr user guide and documentation
site_url: https://patchcablemgr.com

repo_url: https://github.com/patchcablemgr/pcm_code

### Build settings ###

theme: readthedocs

nav:
  - Introduction: index.md
