### Site metadata ###

site_name: PatchCableMgr
site_description: PatchCableMgr user guide and documentation
site_url: https://patchcablemgr.com

repo_url: https://github.com/patchcablemgr/pcm_code

### Build settings ###

theme: readthedocs

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Dashboard: dashboard.md
  - Templates: templates.md
  - Environment: environment.md
  - Explore: explore.md
  - Archive: archive.md
  - Admin: admin.md
  - FAQ: faq.md
  - Changelog: changelog.md
