### Site metadata ###

site_name: PatchCableMgr
site_description: Starter template for a MkDocs docs site on GH Pages - including CI
site_url: https://patchcablemgr.com

repo_url: https://github.com/MichaelCurrin/mkdocs-quickstart
edit_uri: edit/master/docs/docs

### Build settings ###

theme: readthedocs

nav:
  - Introduction: index.md
  - Installation:
      - Overview: installation/overview.md
      - Hosted: installation/hosted.md
      - Self-Hosted: installation/selfhosted.md
  - Markdown Cheat Sheet: cheatsheet.md